### ISSUE TITLE
Use right colors for app system iconography

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#17]
Material design has some [guidelines](https://material.io/guidelines/style/color.html#color-usability) for texts and icons colors in every theme.

I think using the right colors will make it look better than the current full-black icons in light theme (for example).

**Comment by staber** [comment]
Are you referring to the menu items or the bottom sheet, image actions?

**Comment by jahirfiquitiva** [comment]
@staber both

**Comment by staber** [comment]
weird... The menu items are all vector drawables, with Material fill colors, but the style/theme may be overlaying some tint. I'll check it again with the color picker like you mentioned.

**Comment by jahirfiquitiva** [comment]
@staber 

Ok thanks. You could also consider tinting them programmatically to ensure they have the right colors.

Btw, I would like to mention that I like the app in general. Great work. Small details that I already mentioned.

Thanks

**Comment by staber** [comment]
fixed in v0.5.0

**Comment by jahirfiquitiva** [comment]
@staber 

This isn't fixed yet. Right color should be #8a000000 (black 54% opacity) ... but seems like it is #de000000 (black 87% opacity)

**Comment by staber** [comment]
What are you using to evaluate transparency? The one's I've tried don't include it.

**Comment by jahirfiquitiva** [comment]
@staber

I must admit that I used my eyes only

But made this super quick picture on paint.net

Top-left is the color icons should be using. Top-right is the colors I thought they were using

And bottom is the actual color picked with [Pipette](https://play.google.com/store/apps/details?id=com.ochs.pipetteplus)

There's still a notable difference between the color they should be and the color that they use.

![colors](https://user-images.githubusercontent.com/10360816/28650865-2314ce14-7244-11e7-9f51-21ca36cd4f1b.png)

**Comment by jahirfiquitiva** [comment]
Hey @staber this hasn't been fixed. Can you open the issue again?

**Comment by staber** [comment]
Material Dark background color is #303030 which is what I'm using for dark theme and the icon colors for light theme. 

EDIT: I'm using [Pixolor](https://play.google.com/store/apps/details?id=com.embermitre.pixolor.app&hl=en) to inspect live.

**Comment by jahirfiquitiva** [comment]
@staber

Background colors are fine. Icons colors are not.

As I told you in a previous comments, guidelines clearly say the color for icons should be #8a000000 (black 54% opacity) which is way different than #303030

Also, you cannot use a color picker to check transparency, but in a picture I uploaded in a previous comment, you can see the differences.

**Comment by staber** [comment]
I just tested some icons at black 54% and they appear very light grey. Pixolor reads them as #737373. I'll try them like this myself until the next release and see how well they go with the app.

**Comment by jahirfiquitiva** [comment]
@staber 

Ok, hope the right color make it to release

**Comment by staber** [comment]
fixed in [v0.5.2](https://github.com/dodgingpixels/Optic/releases/tag/v0.5.2)

**Comment by jahirfiquitiva** [comment]
@staber Not completely fixed. Settings still show full black icons. Also the texts are full black if I'm not wrong :/
